name: 'scp-deploy'

description: 'A simple GitHub Action that deploy files to a remote server via SCP'

author: 'GitHub'

inputs: 

  local_path:
    description: 'Path to the file or folder you want to deploy'
    required: true
  
  server_path:
    description: 'Path on the server where you want to deploy'
    required: true
  
  host:
    description: 'Enter host name or IP address'
    required: true
    
  port:
    description: 'Enter SSH port on the server or leave empty if the port is 22 by default'
    required: false
    default: 22
    
  username:
    description: 'Enter username'
    required: true
    
  ssh_key:
    description: 'Enter private ssh key'

  init_npm:
    description: 'Use if you need to install npm packages on the server (true/false)'
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'